title: "Mathematical Modeling Course"
author: "Anna Oleynik, and other authors"
logo: "logo.png"
execute:
  execute_notebooks: off  # Ensures notebooks are not auto-executed when building
latex:
  latex_engine: "xelatex"  # Supports LaTeX equations
html:
  mathjax: true
  use_repository_button: true  # Adds a GitHub repository button
  use_issues_button: true  # Allows students to report issues
repository:
  path_to_book: .
  url: "https://github.com/Codeniksson/MATH4SDG"
  branch: main
